if game.PlaceId == 5777099015 then
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Cheese Escape V1", "Synapse")

-- PLAYER
local Tab = Window:NewTab("Main")
local Tab3 = Window:NewTab("Locations")
local Tab2 = Window:NewTab("Credits")
local Section = Tab:NewSection("Player")
Section:NewSlider("Walkspeed", "Changes the walkspeed", 250, 16, function(s)
    game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = s
end)

Section:NewSlider("Jumppower", "Changes the jumppower", 250, 50, function(s)
    game.Players.LocalPlayer.Character.Humanoid.JumpPower = s
end)

Section:NewDropdown("Get Items", "Gives you item in-game", {"White Key", "Red Key", "Yellow Key", "Red Cheese", "Purple Key", "Blue Key", "Board"}, function(currentOption)
    if currentOption == "Purple Key" then
       local key = game.Workspace.Handle
       if key.BrickColor == BrickColor.new("Magenta") then
        game.Players.LocalPlayer.Character:MoveTo(key.Position)
        end
    end
end)

Section:NewButton("Get All Cheeses", "Gives you all cheese's in-game", function()
    for _, v in pairs (game.Workspace.FindCheese:GetDescendants())do
   if v.Name == 'Cheese' then
    fireclickdetector(v.ClickDetector)
         end
     end
end)


-- CLIENT
local Section2 = Tab:NewSection("Stuff")

Section2:NewButton("Open Spawn Door", "Opens Spawn Door", function()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
    fireclickdetector(game.Workspace.Cheese.ClickDetector)
    wait()
end)

Section2:NewLabel("Locked Door Code: 3842")


-- Credits
local Section3 = Tab2:NewSection("Credits")

Section3:NewLabel("Made by IceyTamim - FrostedTamim")

-- Locations
local Section4 = Tab3:NewSection("Locations")

Section4:NewButton("Spawn", "Spawn's Location", function()
    
    end)
end